[tool.poetry]
name = "manifold_clustering_reduction"
version = "0.3.2"
description = "Perform dimensional reduction and clustering on moderately high dimensional data (i.e. mass cytometry), perform clustering, and visualize using Plotly Dash"
authors = ["Miles Smith <miles-smith@omrf.org>"]
license = "LGPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.8"
click = "^7.1.2"
python-igraph = "^0.8.3"
leidenalg = "^0.8.3"
pandas = "^1.2.1"
numpy = "^1.20.0"
sklearn = "^0.0"
scipy = "^1.6.0"
umap-learn = "^0.5.0"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
cairocffi = "^1.2.0"
click = "^7.1.2"
cmake = "^3.18.4"
fastparquet = "^0.5.0"
flake8 = "^3.8.4"
hdbscan = "^0.8.27"
python-igraph = "^0.8.3"
isort = "^5.7.0"
leidenalg = "^0.8.3"
matplotlib = "^3.3.4"
networkx = "^2.5"
numpy = "^1.20.0"
pandas = "^1.2.1"
scipy = "^1.6.0"
seaborn = "^0.11.1"
sklearn = "^0.0"
snappy = "^2.8"
tensorflow = "^2.4.1"
umap-learn = "^0.5.0"
pytest = "^6.2.2"
pytest-cov = "^2.11.1"
tox = "^3.21.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
